package com.SkillExchange.notification.model;

public enum NotificationType {

    EXCHANGE_REQUEST_RECEIVED,
    EXCHANGE_REQUEST_ACCEPTED,
    EXCHANGE_REQUEST_REJECTED,
    EXCHANGE_REQUEST_CANCELLED,

    SESSION_SCHEDULED,
    SESSION_REMINDER,
    SESSION_COMPLETED,

    EXCHANGE_COMPLETED,

    CREDITS_EARNED,
    CREDITS_SPENT,

    REVIEW_RECEIVED
}